 CREATE TABLE "COVID19"."RESERVATION" 
   (	"NO" NUMBER, 
	"GUBUN" VARCHAR2(500 BYTE), 
	"VACCINE" VARCHAR2(500 BYTE), 
	"HOSPITALADD" VARCHAR2(500 BYTE), 
	"RSDATE" VARCHAR2(300 BYTE), 
	"REGDATE" DATE,
	"MEMBERID VARCHAR2(300 BYTE)"
   );
   
   
   CREATE SEQUENCE  "COVID19"."RESERVATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;


///

CREATE TABLE "COVID19"."REPLYBOARD" 
   (	"NO" NUMBER, 
	"SUBJECT" VARCHAR2(500 BYTE), 
	"REGDATE" DATE, 
	"REF" NUMBER, 
	"RESTEP" NUMBER, 
	"RELEVEL" NUMBER, 
	"READCOUNT" NUMBER, 
	"CONTENTS" VARCHAR2(2000 BYTE), 
	"MEMBERID" VARCHAR2(100 BYTE)
   )
   
   
   CREATE SEQUENCE  "COVID19"."REPLYBOARD_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;

   
   